node-preset: &node # Used internally to share configuration, ignored by travis.
  language: node_js
  node_js:
    - "10"
  cache:
    directories:
      - node_modules
stages:
  - test
  - build
jobs:
  include:
    - name: Unit tests
      stage: test
      <<: *node
      script: yarn lint && yarn test --runInBand && yarn check-locales && yarn check-fixtures
    - name: Web build
      stage: build
      <<: *node
      script: yarn build
      before_deploy: ./scripts/ci/add_ssh_key.sh
      deploy:
        - provider: script
          repo: cozy/cozy-banks
          skip-cleanup: true
          script: yarn cozyPublish && yarn uploadStaticFiles
          on:
            branch: master
        - provider: script
          repo: cozy/cozy-banks
          skip-cleanup: true
          script: yarn cozyPublish && yarn uploadStaticFiles
          on:
            tags: true
    - name: Android build
      stage: build
      os: linux
      dist: trusty
      language: android
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - tools # needs to be first to get new package versions
          - tools
          - platform-tools
          - build-tools-26.0.2
          - android-29
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install: nvm install 10
      before_script:  ./scripts/ci/android_before_script.sh
      script: ./scripts/ci/android_script.sh
      after_success: ./scripts/ci/android_after_success.sh
      if: tag IS present OR (type = push AND branch = master) OR (branch =~ /release/ AND commit_message =~ /(\[apk\])/)
env:
  global:
    - MATTERMOST_CHANNEL='{"dev":"gangsters","beta":"gangsters,publication","stable":"gangsters,publication"}'
    # cozy-bot GH_TOKEN
    # to generate yours : travis encrypt GH_TOKEN=<your_GH_TOKEN> -r cozy/cozy-banks
    - secure: "qhjOq0o2CXJvexLTHlBdmzHPrJr7fPOvpwvOdXBy/0XtoNgAoypmzkjCTlgQpXLo0qJMet0JddMgfdVV79yPiQ9Er0eaMkG6YjHv25yyuJU1ZMvR3Ehza5eLPAUr55qLRA9Uz/BVhPp2SCJr5Sq5nThcdiY3vbPHvKIYZh37qKETHxqiaJGEtT5I4Bz0Rrb+Mh49vLN0d50BBRSPipR0TH2a6oeQbxRw0OyXXkJsw1I1QJr9MLbHptWH8f6uZoTMhNBXtTMxwgGleYZuwZVivZm0/lXDi+A892Cc610C3zAjAJN3tGtIT5yylXK/c3sB/e14rI80v1koL+HkKIEPl+Kd46k1eHWgIvP2uK80Bhr9dB/XdRLM9j6hfIrJV9sObJSXucMXxK8WlPzuOr9G8t+6SMjrVgZ/YhZwVsTFgRoQQtvU7bXLRPn+04E1tYPPrwCdhRRL/JPRceI1K5Pl3VeV7JKb0Z8A989jCAO7mmPojPj/J79FwzDllkT2+LuJVqmg2eeSpe9I/NyMG9uaEwxVv89hoEdLM950pXnBU6yODcOJqA3gzg+F8y2YqJA8CIN3gOWXjYpgyNqUoGCGxXRD/HkJIwFWY2iY2I6ShBGIZsuVg+sTa3KGrulOCfWFRfxLjzKLed8JGJhSOzMosZPWsXMa+TfQKbn3iDVD8nQ="
    # MATTERMOST_HOOK_URL
    - secure: "i40PC82nF00ixRI/uArDG48tY99DYg4/gu9EpRXK8BeV/Uh6WVT5MpBbd8JEyf3fLZFXVwdbBPrsEUw4aX2fdfbueRqaigLbYz3rejNGL2YjE28ZBmFQeoPviHz8cOJepcjUrgggkiyD14qvAyoPJCEo/pPx1ZCsZ2UCQHu5SIw9Mtf2kvspgNyhpl3ktm/L4wh+8huRE7/Zn6SKStps5F7MWrUp5zZ6ZovHLl8ti71p2KhCCIJL30PGoh58O3aH3t7LY2bUetQS6p0a4OxWUF3AE5wakzffvqvrHqMI4ulkREYq/J6b7ITkHhxL9V1ndCvQyw4aC5OUR4Dl3GznSfkvby9NNyNcK4lxeOgjejvSrmPV5gEmCPjnpyijkMidy/5OMOCeQIXtWw7Cly+Mnj1kWz6bFnLncs1SBqdxUSUa+jTPZ8tklAiz4hdkGgtPxpovyo4iQdNQVmL8y2v7XWuXvpdGTEuZgGIubH3+HDOwa3dawC6BglnY1W0sp3hvYUaEKyPolP/mCV9HRSZ0Aa1zjjNW2brbUaEJ6w1UMT7XwQQQtb35K+zQSBCn9jfNyuDdotsh+mJEILk0tsB3aYcVnvLUKChpTt23bV5sMxga0F/Mmmwb8y8DWE8u7ADWDjzdDnoaqInSj9RAYVgFguhWpZhVs6yuGd16Bi7kvoU="
    # RUNDECK_TOKEN
    - secure: "rwvCE17fZRfx9wi692wU+ox/oKx8dSeit5WbPxq6c6Jj39IfaKaeXBgDVaG1HsvY6RhhXKJ6t1hrUGNzLOJdPDvfkQKEPDlKgbJoFstCke2aj3guOLx/aSzdoB2fUTWjaIKtrVZFtC60YK9dr1g9UzrFru0Fe6JP/XN2fIqqR3wwzWln1bYVINwWPj+HQNZO9YIejKei7ooSO+FSf/C9nqMkELNv89x8yAZASGejfhayPvRlbT2CF8Ym0GkqEBRNRqHfURGE4m9mUEPIv7vQ0uPnH9dwwQrZf6KXCHIoG+O5sH54V4M28FBMTHYF/3GflcJFm3qNnffoOcUl5/K3LQWKbeShw7W+BjuPbjXSLZICnENWeXHmvjYjUN4niUxwWewM+a5k+5LgcEd/ZLrWui6KFAjl1SGqu97hBRPCDelF/ssTfh0UwM4brSQ3Dgi3bLex49VDPmA63/vtH5HRQ+7EM+FcaEnFsaA5cUaGOQAExIySSzimyjSF5seOJcrH3QmmkTt8qsWrYMCqes6bMmx2gOgQQ2vAvxrtJyunhriiEKWTnLOGwdB7AyS5A6QF1K3FodLAqDYwQgkSYSS4isv2RNT5Bilk9hJ1IVs82ZgepOpwkhygae2/2n4ZUv9ynol0f083BG+vNVb6b79o4ZHrsfTQatu9Mlrorug6a0Y="
    # REGISTRY_TOKEN
    - secure: "q0e3QfSHzD7u03W/uRmZ/1CgwLrdO2GuWD/9fPXTYXI9vnu0Z4xPLGHv0zzshgdH4qNyIJ+74KCfk2ev6FvG+8Z15qNkdbwLjQxn3TDK48dfjC8C1SWfa55r2hjMo/qYXgLhBpdaVeGLyvpvmmKB+MsqKVugr1V41iBLfXNustJ2smvCkjKiRWH7Jl6jeMWQ+paL5WccK6DF5GqoPc3RCdSoXNhhPOelmo2NI/XF1MFRNToc5Fl5yIquivJdb7nA1UTB+DKZOX0I4+6sJpecuseNFdnm938QuMRaRgiKChqH+lesMSDy9+m5qp/ftByXdZIUxqxeROxNF5sVG1IxC6CNnpqsltNAAnGOHT9laQaWrfjQHUMb7pC5fjR1JN5Y3N5ZspLlnDKeEpZc3muqbyRcJDDRl2lAxgtt1MDyOD3u2IuCwa8xKysZzDHBjIQDChr01mWmTb3tOt7iwSc7HekOnfa2VHvlQfiWD/JSKLRLGoX3GC/RljuIC7SxufUojV9vn2heROPk9b95wnHGce3rmHPuECfxuLAU2PN84S9j+j371AJ4/UsQhGV9Gyl3Bgua/6X82pooN4/Q/0RURJrQ8DUPkQ1wbDHCOeaDB97ZvcQi3bGUh+AiElSaHS+V7c6kne7QRmCPcn9NnlKmz7YPd141922WMIUunoc7guI="
    # ENCRYPTED_KEY
    - secure: "MkxSVyjNwHPfuCA4kdrTeBRbmDV2j4wcvD7416ykZYSh2ixHnSFxDyi5cabCW2Rzz4+JDh2GUBL/mIJr5PvqKHRRV5Ehtu/fN8b53PjmcuREBzK3JMsuWtT0PMqfM633l0YAFhqLkoyDsRzpKofbw9LMQumapSOcHnODONoTgPfr0RixP7yaGkARB4ythdiCfbSK6BceS1q+XXfi2/aZh915l9Edjhs5T/3tJt8ufr8JuBV3dILk/3G7tgku6YI7SDNum6u6FVny+o23e+vzfkgDPDXVPECplAWaAt8VzasDafyVR1C4jFm+QY0D5QOnhcUmFZ04P1ng3690AI67QVgk+UUO3kpiFlKO4LhkKNf6z+gnGmYI87yz0VywcNrMwwiZC7f/yJee7mtF2YGndiO8NCISCORe3fi/gh19SOB4je8+g/CVWYU6tz7D5Ci5UKBMglnPP1o/TsO2J7VEbs9HqwfsBxghLo988KDeqtIaXCLY3Buro29jGgbYLcT9h7qG/Q3F1b4Z5Dga4FzPUQ4D11yXbv1pip1UNTwTWzyyY5YemIr0M7c4Z6JrndrrNact/iIUOW3rBoXVuWnltHfmVyXIfognBDGiB4YUHDdhSZd4etIQxID9cbEfdsL2xycrpH2bdqX9ePYK+DahBmx+qUESVpcMvW4cTYJygIY="
    # ENCRYPTED_IV
    - secure: "iz1NO2t2ZSEpc7CMz2CtMNXyFa4FTLRZu9wPlnx1IwXHTworqJ8ENSAv4kDHOFYWXubHb52c2c3dMMLLZtHxRpTtnHRvEDCHzLdc6RP5wnoOLogtfSzD140g94+iPEaXfg6hJ/Wv1nE+iBTtfDTpRMy8e/i+InU4af3FcwqMJW1oroslgd9ubZV+KUuv4nHZNOxTW67lLUQ2iRI3b7Ewjo/zkhMgCGLz4lnSO6KnspgKQ6VUA+UeV+Xx28Y5mDpH2ouhfajji6xUHptoB9AG2WZf6GfpOOMB5gxSnGNf6BiVal/TyG0unMiUy6dij+6XYnSpmG6EWna7nR35M4PD7pIwiOzcvwVwvZ4j5GnXIoIOA12Wd9vP8iPmji509slgsut00qFbgU4Uxii8ElGuDdChGzdVXuSYUBLtX7ldMcYKLMckyn/wBnWndQrDNv5jDROms+8YxNIFbm4kRM3ynt1xMFtm2v43Cj/VQ+ZwFV0cr3Y6y4QoThBrnuFXHIXJfe8HsuYZaGPpa9Jf1SDRNut7ClmvGm5+Yf+gkG1Csm82perZ1SQBtyBdtEPF71zQ1ktWYduQrG6jLb4On5zcGZ+CmPdjOopNatq6AatpFYpuZkVyhTbyn626fRIOCgbyDkgSS6yBweUB5eq8EW7Fdu8jqB0fR5+WKISe7m6dpTg="
    # ANDROID_KEY_PASS_PASSWORD: travis encrypt ANDROID_KEY_PASS_PASSWORD=<password> -r cozy/cozy-banks
    - secure: "lWYmzyQM7sIKuoJIIiljRH2dOTXsna4qvC+rZeAYtxlHRgEZlObL5S4St2oAv+FGMHa8j1hZfxTBotqbKrVtjBuW0Sc3lezw/+WbB3MyUcFJF2rPGXOEWKDK3NTFyT2j0faO0XjPZMUtjHBZIcAMsHyBQCVrwIcIPICYoS8zFHYeAfI1ZbNSXQJzBkoEvR4yj7zDqPp9k7EZ12zvzBlnH8WiHSfjo8MjBWajQ4ZtCBHNO0MpVlQ30KKc8K8P0pkB55BahzX+6nBLFgIC5I5r+1QzZ5KjRBzMm8D/F7wn0jDMnHb5imJ8eZky+gPT6s4QF4jrLLOxwLelFqSQSSwpMH9+qfYTzNrhRFfBbi/xn/HQRje6bJBzD5stp5pOM6k3GWltK67KZKq7cGdAvSAOtKWdmr3NKny/q8LG6X2iQWOETcWobGv6BYjKvQTO9SVT+dd8Cg77s81Q/TMhB+If6g6mcvfsTUocyrXqvcf3mFcMKnadyAX89Ccz5f3yVYMhCLnU7F8FNsZYFpgKJ1HB9zXSsAkZVAL+8fX1iRZEGw1xKHwGO7yh5utxgQHAUfrqHGP8qdTpct1pfHF01P+ybt1k2rnLXAM3qDPg+fDlm1oEYwzrp/uRxmHlG50o5YILSGZEKk0OArcYKezToVWfNMmnzmQCY0O13dvgd/F9cFw="
    # ANDROID_KS_PASS_PASSWORD: travis encrypt ANDROID_KS_PASS_PASSWORD=<password> -r cozy/cozy-banks
    - secure: "eW3p+Pkd4a6GtvKaZmIVqnvLwZKQHopc11PmiQAr3Hn8wczNaQBSsHJNQSqzzH5aAw3Ou1XRRASdqzxb2Kc+TtUdLKV2WT25SQYz8knx9G7et76zNnoCoKG5xR3Forbphi8KnnajtzL1dBr1H7ebkB2nzBaXWTR3YginRxaLU4gEGeJ3C0K4PVy4P9OOwVsxxOWmEz+p0ahLYQbX5XsRG3bcDb3XJ5/XVdTzEa0iFeK1Ukt0QqQ5AF4h3wI4m10ldNCqQDl8JEYqJQUb+OW1yqEQTHd5J2FHwkH9aVolTmWOka+okujeB+oIdY94k3RUiwhiX9QBS+S8z8SxynzQ53z8JjVzyiRikCocC0AMVTBOoLS0squL1ZVUIR2XCM0oNPiAY8nq9oooStntbcyyNY+eREueq6m91fFfnZr1mXfNDtDNKY9AbNR7lP+YhHTdduRV719HLFwcRIHoRhkD9fykcZ8RSYqcwPS+eX2t90q76MRQXzr4du60KSNtbAV9aGr9dk7pFk9SSYo7JZ3xUEXaaQ7POmLnTYW8sR8NDnrnk59HiVR0jMPVQ5uAvtx+h0bPsSW043NWroFgb+J/wTJD2ntfr5fXTFs4WNE2dfViZX2bVMaDv3l3HODLeMmMv9fJO6CSSwHRoFqh4D9OrI479gkiYpjwTXFSJy/VnVg="
